'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NetworkMessagingUIMockUps.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        '''&lt;html xmlns:fb=&quot;http://www.facebook.com/2008/fbml&quot; xmlns:og=&quot;http://opengraph.org/schema/&quot;&gt; &lt;head&gt;
        '''        
        '''&lt;meta property=&quot;og:title&quot; content=&quot;CenterEdge - Last Chance, Act Now &amp;amp; Save through July 15, 2014&quot;/&gt;
        '''&lt;meta property=&quot;fb:page_id&quot; content=&quot;43929265776&quot; /&gt;
        '''&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1&quot; /&gt;        
        '''    	&lt;!-- NAME: 1:2 COLUMN --&gt;
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Message1() As String
            Get
                Return ResourceManager.GetString("Message1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        '''&lt;html xmlns:fb=&quot;http://www.facebook.com/2008/fbml&quot; xmlns:og=&quot;http://opengraph.org/schema/&quot;&gt; &lt;head&gt;
        '''        
        '''&lt;meta property=&quot;fb:page_id&quot; content=&quot;43929265776&quot; /&gt;        
        '''        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''        &lt;!-- Facebook sharing information tags --&gt;
        '''        &lt;meta property=&quot;og:title&quot; content=&quot;4th of July 2014&quot;&gt;
        '''        
        '''        &lt;titl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Message2() As String
            Get
                Return ResourceManager.GetString("Message2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        '''&lt;html xmlns:fb=&quot;http://www.facebook.com/2008/fbml&quot; xmlns:og=&quot;http://opengraph.org/schema/&quot;&gt; &lt;head&gt;
        '''        
        '''&lt;meta property=&quot;og:title&quot; content=&quot;CenterEdge - Upgrade Now &amp;amp; Save through July 15, 2014&quot;/&gt;
        '''&lt;meta property=&quot;fb:page_id&quot; content=&quot;43929265776&quot; /&gt;
        '''&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1&quot; /&gt;        
        '''    	&lt;!-- NAME: 1:2 COLUMN --&gt;
        '''        &lt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Message3() As String
            Get
                Return ResourceManager.GetString("Message3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        '''&lt;html xmlns:fb=&quot;http://www.facebook.com/2008/fbml&quot; xmlns:og=&quot;http://opengraph.org/schema/&quot;&gt; &lt;head&gt;
        '''        
        '''&lt;meta property=&quot;og:title&quot; content=&quot;CenterEdge Advantage 14.1 Released!&quot;/&gt;
        '''&lt;meta property=&quot;fb:page_id&quot; content=&quot;43929265776&quot; /&gt;
        '''&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1&quot; /&gt;        
        '''    	&lt;!-- NAME: 1:2 COLUMN --&gt;
        '''        &lt;meta http-equiv=&quot;Conte [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Message4() As String
            Get
                Return ResourceManager.GetString("Message4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        '''&lt;html xmlns:fb=&quot;http://www.facebook.com/2008/fbml&quot; xmlns:og=&quot;http://opengraph.org/schema/&quot;&gt; &lt;head&gt;
        '''        
        '''&lt;meta property=&quot;fb:page_id&quot; content=&quot;43929265776&quot; /&gt;        
        '''        &lt;!-- This is a simple example template that you can edit to create your own custom templates --&gt;
        '''        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''        &lt;!-- Facebook sharing in [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Message5() As String
            Get
                Return ResourceManager.GetString("Message5", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
